name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点运行

env:
  TZ: 'Asia/Shanghai' # 设置时区为UTC+8

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 检查出您的仓库
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # 选择适当的Python版本
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # 安装您的Python依赖
      - name: Run script
        run: python bingpaper2.py # 运行您的Python脚本
        env:
          TZ: 'Asia/Shanghai' # 设置时区为UTC+8
